---
title: "Seep Explorer"
author: "Serena Geroe"
date: '`r format(Sys.time(), "%d %B %Y")`'
output: html_document
---

```{r LoadLibraries, error=FALSE, message=FALSE, warning=FALSE, echo=F}
# This section of code installs and loads the required packages

# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(tidyverse,readxl,knitr,sf,devtools,here,leaflet,htmltools,
               leaflet.extras,mapview)

# Define method of table generation (whether kable or xtable) for best formatting
doc.type <- knitr::opts_knit$get('rmarkdown.pandoc.to')
if (is.null(doc.type)) {doc.type <- "html"}

# Set global knitr chunk options
if (.Platform$OS.type == "unix") {
  # Do not specify Cairo device for MacOS
  knitr::opts_chunk$set(echo = F,warning = F, message = F,
                        fig.align = 'center', out.width = '100%', dev = "png", dpi = 150)
} else {
  knitr::opts_chunk$set(echo = F,warning = F, message = F,
                        fig.align = 'center', out.width = '100%', dev = "png", dpi = 150,
                        dev.args = list(type = "cairo"))
}

# Plotting preferences -------------------------------------------------------
# Leaflet tile options; set both to T if caching
save.imap      <- F # Save the interactive map
useCachedTile  <- F # Use cached tiles
useCrossOrigin <- F # Use cross origin
```  

# Interactively explore methane seep data 
The map below allows for the interacitve exploration of seep data. Base maps may be changed and other layers may be toggled on/off using the layer controls below the map inset.  

```{r CreateSimpleFeatures, include=FALSE}
# Read seep regions
seep.regions <- read_excel(here("Data/2013_SHIMADA_SaKe_SEEPRegions.xlsx")) %>%
  mutate(type = "Seep")

# Read uncertain regions
uncertain.regions <- read_excel(here("Data/2013_SHIMADA_SaKe_UNCERTAINRegions.xlsx")) %>%
  mutate(type = "Uncertain")

# Convert location data frame to simple feature (an object with spatial/geographic information)
seeps <- bind_rows(seep.regions, uncertain.regions) %>% 
  st_as_sf(coords = c("Lon_M","Lat_M"), crs = 4326) 
```

```{r SeepLocationsROV}
seeps.rov <- read_csv(here("Data/seeps_rov.csv")) %>% 
  st_as_sf(coords = c("long_r","lat_r"), crs = 4326) 
```

```{r LeafletNasc, echo=FALSE}
# Leaflet options
# https://rstudio.github.io/leaflet/

# Info on tile caching
# https://bhaskarvk.github.io/leaflet.extras/reference/TileCaching.html

# Create color palette for seep types
seepPal <- colorFactor(c("red","blue"), c("Seep","Uncertain"))

# Create leaflet map
i.map <- leaflet() %>% 
  # Enable tile caching
  enableTileCaching() %>%
  # Add provider tiles; # http://leaflet-extras.github.io/leaflet-providers/preview/index.html
  addProviderTiles(providers$Esri.OceanBasemap, 
                   options = tileOptions(useCache = useCachedTile, group = "Esri Ocean (default)",
                                         crossOrigin = useCrossOrigin)) %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB Positron",
                   options = tileOptions(useCache = useCachedTile, 
                                         crossOrigin = useCrossOrigin)) %>%
  addProviderTiles(providers$OpenMapSurfer.Roads, group = "OpenMap Surfer Roads", 
                   options = tileOptions(useCache = useCachedTile, 
                                         crossOrigin = useCrossOrigin)) %>% 
  # Add seep locations from acoustics
  addCircleMarkers(data = seeps, radius = 5, color = "#000414", stroke = TRUE, weight = 1,
                   fillOpacity = 0.75, fillColor =  ~seepPal(type), label = ~htmlEscape(type),
                   group = "Seeps-Acoustics") %>% 
  # Add seep locations from ROV
  addCircleMarkers(data = seeps.rov, radius = 5, color = "green", stroke = TRUE, weight = 1,
                   fillOpacity = 0.75, label = ~htmlEscape(sci_name),
                   group = "Seeps-ROV") %>% 
  # Add graticule
  addGraticule(interval = 2, group = "Graticule") %>% 
  # Add legends
  addLegend("bottomleft", colors = c("red","blue"), values = c("Seep","Uncertain"),
            labels = c("Seep","Uncertain"), title = "Seep type", opacity = 1) %>%
  # Add extras
  addMiniMap(position = "topright") %>% 
  addScaleBar(position = "bottomright") %>% 
    # Add layer controls
  addLayersControl(
    baseGroups = c("Esri Ocean (default)","CartoDB Positron", "OpenMap Surfer Roads"),
    overlayGroups = c("Seeps", "Graticule"),
    options = layersControlOptions(collapsed = TRUE)) 

# Save Leaflet map to HTML file
if (save.imap) {
  mapshot(i.map, url = here("Output/interactive_explorer.HTML"))
}

# Display map
i.map
```